---

- paru:
    - zsh
    - lsd
    - wget
    - unzip
    - rsync
    - figlet
    - keyring
    - neofetch
    - btop
    - noto-fonts
    - noto-color-emoji-fontconfig
    - ttf-hack
    - ttf-meslo-nerd-font-powerlevel10k
    - meld
    - joplin-appimage
    - yubico-authenticator
    - tmux
