---

- yay:
    - zsh
    - lsd
    - wget
    - unzip
    - gum
    - rsync
    - figlet
    - keyring
    - neofetch
    - btop
    - noto-fonts
    - noto-color-emoji-fontconfig
    - ttf-hack
    - ttf-meslo-nerd-font-powerlevel10k
    - telegram-desktop
    - spotify
    - meld
    - discord
    - joplin-appimage
    - rpi-imager
    - mkinitcpio-pkcs11
    - yubico-authenticator
    - zoxide
    - tmux

