---

- paru:
    - neovim
    - dbeaver
    - lazygit
    - miniconda3
    - conda-zsh-completion
    - direnv
    - go
    - aws-cli
    - ripgrep
    - snappy
    - tree-sitter
    - yamllint
    - npm
