---

- link:
    ~/.config/hypr:
      force: true
      glob: true
      path: gui/hypr/hypr

- paru:
    - pciutils
    - hyprqt6engine
    - aquamarine
    - hyprcursor
    - hyprgraphics
    - hyprland-guiutils
    - hyprtoolkit
    - hyprwire
    - tomlplusplus
    - xorg-xwayland
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal
    - hyprpicker
    - hyprpolkitagent
    - archlinux-xdg-menu
    - hyprshot
    - hyprlock
    - ark
    - dolphin-plugins
    - kio-extras
    - kio-fuse
    - emote
    - ydotool
    - emote
    - papirus-icon-theme-git
    - satty
    - gimp
    - clipse
    - jq
    - imagemagick
    - power-profiles-daemon
    - hypridle
    - seahorse
    - wl-clipboard
    - phinger-cursors
    - brightnessctl
    - playerctl
    - inotify-tools
    - wf-recorder
    - equibop-bin
    - yubico-authenticator
    - joplin-appimage
    - firefox
    - ttf-font-awesome
    - fastfetch
    - ttf-fira-sans
    - ttf-fira-code
    - ttf-firacode-nerd
    - fuse2
    - gtk4
    - python-gobject
    - hyprland
    - dms-shell-bin
    - qt5ct
    - khal
    - qt6ct-kde
    - cava
    - i2c-tools
    - qt5-wayland
    - qt6-wayland
    - cliphist
    - qt6-multimedia
    - accountsservice
    - matugen
    - python-pywalfox
    - greetd
    - greetd-tuigreet
