---
- defaults:
    links:
      relink: true
      create: true

- clean: ['~']
- create:
    - ~/.tmux/plugins
    - ~/.config/yamlfmt
    - ~/Documents
    - ~/GIT

- shell:
    - command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- link:
    ~/.tmux.conf: tmux.conf
    ~/.tmux/plugins/tpm: tpm
    ~/.config/nvim: nvim
    ~/.config/yamlfmt/.yamlfmt: yamlfmt
    ~/.aliases: aliases
    ~/.zshrc: zshrc
    ~/.p10k.zsh: p10k.zsh
    ~/.gitconfig: gitconfig
    ~/.config/rofi: rofi
    ~/.config/ghostty: ghostty
    ~/.config/hypr:
      force: true
      glob: true
      path: hypr
    ~/.config/waybar: waybar
    ~/.config/dunst: dunst
    ~/.config/wlogout: wlogout
    ~/.oh-my-zsh/custom/plugins/fzf-zsh-plugin: fzf-zsh-plugin
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: zsh-autosuggestions
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: zsh-syntax-highlighting
    ~/.oh-my-zsh/custom/themes/powerlevel10k: powerlevel10k

- shell:
    - [
      yay -S --noconfirm
      tmux
      direnv
      nvim
      go
      node
      lazygit
      ripgrep
      snappy
      tree-sitter
      yamllint
      zsh-completion
      npm
      awscli, Installing required packages]
